### ISSUE TITLE
Our foreground color doesn't pass contrast checks

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#146]
Our foreground color is #1e6b52.

According to: https://webaim.org/resources/contrastchecker/?fcolor=1E6B52&bcolor=FFFFFF we don't pass AAA test for normal size text. The foreground color is used in links so we'll need to modify the link color. I suggest using the HTML5 standard #0000EE blue.

Personally I'm having trouble differentiating links from text on our white background, at a glance. It might make sense to go with a less dull-green color. My thought is to use something like the standard blue, rather than try to be super-branded.

Compare to: https://webaim.org/resources/contrastchecker/?fcolor=0000EE&bcolor=FFFFFF

**Comment by wwarriner** [comment]
Reference for CSS in Material here: https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss

**Comment by wwarriner** [comment]
Sample: 
![image](https://user-images.githubusercontent.com/6930772/160701493-dbac55d8-d55b-4dab-b20b-575c67721a3f.png)

**Comment by wwarriner** [comment]
```css
.md-content a {
  color: revert;
}

.md-content a:visited {
  color: revert;
}

.md-content a:hover {
  color: revert;
  border-bottom: 1px solid;
}

.md-typeset .headerlink:hover {
  border-bottom: none;
}
```
