### ISSUE TITLE
Consider moving Table of Contents to the left-hand side of the page

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#610]
Following from here: https://stackoverflow.com/a/71133751

In your custom css file, write:

```css
.md-sidebar--secondary {
  order: 0;
}
```

And in your mkdocs.yml, write:

```yml
extra_css:
  - assets/<custom_css_filename>.css
```
