### ISSUE TITLE
UAB logo fix for all browsers

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#620]
In `extra.css` line 8 change

```css
/* logo fix */
.md-header__button.md-logo :is(img, svg) {
    height: 1.2rem;
    width: auto;
}
```

to 

```css
/* logo fix */
.md-header__button.md-logo :is(img, svg) {
    height: 1.2rem;
    width: auto !important;
}
```
